# Generated by Django 5.1.3 on 2025-05-14 02:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_asig', models.CharField(max_length=100)),
                ('tipo_asig', models.CharField(choices=[('area', 'Área'), ('subarea', 'Subárea')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_doc', models.CharField(max_length=100)),
                ('apellidos_doc', models.CharField(max_length=100)),
                ('tipo_documento_doc', models.CharField(max_length=5)),
                ('numero_documento_doc', models.CharField(max_length=20)),
                ('email_doc', models.EmailField(max_length=254)),
                ('telefono_doc', models.CharField(max_length=20)),
                ('direccion_doc', models.CharField(max_length=200)),
                ('fecha_nacimiento_doc', models.DateField()),
                ('estado_doc', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_est', models.CharField(max_length=100)),
                ('apellidos_est', models.CharField(max_length=100)),
                ('email_est', models.EmailField(max_length=254)),
                ('tipo_documento_est', models.CharField(max_length=5)),
                ('numero_documento_est', models.CharField(max_length=20)),
                ('telefono_est', models.CharField(max_length=20)),
                ('direccion_est', models.CharField(max_length=200)),
                ('fecha_nacimiento_est', models.DateField()),
                ('estado_est', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('graduado', 'Graduado')], max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionAspecto',
            fields=[
                ('id_eva', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_eva', models.CharField(max_length=50)),
                ('ponderacion_eva', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_gra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_gra', models.CharField(max_length=20)),
                ('representacion_gra', models.CharField(max_length=10)),
                ('anio_gra', models.IntegerField()),
                ('cantidad_grupos_gra', models.IntegerField()),
                ('cantidad_asignaturas_gra', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id_per', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_per', models.CharField(max_length=50)),
                ('representacion_per', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('codigo_dane_sed', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_sed', models.CharField(max_length=100)),
                ('direccion_sed', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asi', models.DateField()),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaEstudiante',
            fields=[
                ('id_ae', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_ae', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('excusado', 'Excusado')], max_length=10)),
                ('observaciones_ae', models.TextField(blank=True, null=True)),
                ('id_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asistencia')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_eval', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_eval', models.CharField(choices=[('actividad', 'Actividad'), ('disciplina', 'Disciplina'), ('examen_final', 'Examen Final')], max_length=20)),
                ('nombre_eval', models.CharField(max_length=100)),
                ('fecha_eval', models.DateField()),
                ('ponderacion_eval', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_cal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion_cal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones_cal', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grp', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_grp', models.CharField(max_length=10)),
                ('cantidad_estudiantes_grp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director_grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docente')),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grado')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grupo'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.grupo'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grupo'),
        ),
        migrations.AddField(
            model_name='grado',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.sede'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usr', models.CharField(choices=[('coordinador', 'Coordinador'), ('docente', 'Docente'), ('estudiante', 'Estudiante'), ('padre', 'Padre')], max_length=20)),
                ('activo_usr', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_pad', models.CharField(max_length=100)),
                ('apellidos_pad', models.CharField(max_length=100)),
                ('email_pad', models.EmailField(max_length=254)),
                ('telefono_pad', models.CharField(max_length=20)),
                ('direccion_pad', models.CharField(max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.usuario'),
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id_coo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento_coo', models.CharField(max_length=5)),
                ('numero_documento_coo', models.CharField(max_length=20)),
                ('nombres_coo', models.CharField(max_length=50)),
                ('apellidos_coo', models.CharField(max_length=50)),
                ('sexo_coo', models.CharField(max_length=1)),
                ('telefono_coo', models.CharField(max_length=20)),
                ('correo_coo', models.EmailField(max_length=254)),
                ('direccion_coo', models.CharField(max_length=100)),
                ('fecha_nacimiento_coo', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede_codigo_dane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.sede')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteAsignaturaCursoGrado',
            fields=[
                ('id_est_asig', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grupo')),
            ],
            options={
                'unique_together': {('estudiante', 'asignatura', 'grupo', 'grado')},
            },
        ),
        migrations.CreateModel(
            name='AsignaturaDocenteGrupo',
            fields=[
                ('id_adg', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.docente')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grupo')),
            ],
            options={
                'unique_together': {('id_grupo', 'id_asignatura')},
            },
        ),
        migrations.CreateModel(
            name='PadreEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.padre')),
            ],
            options={
                'unique_together': {('padre', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='DocenteSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.docente')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.sede')),
            ],
            options={
                'unique_together': {('docente', 'sede')},
            },
        ),
    ]
