# Generated by Django 5.2.1 on 2025-05-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='id_asig',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='id_area',
        ),
    ]
