# Generated by Django 5.2.1 on 2025-05-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_rename_nombre_asig_asignatura_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo',
            new_name='tipo_usr',
        ),
    ]
