# Generated by Django 5.2.1 on 2025-05-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_rename_id_asig_asignatura_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignaturadocentegrupo',
            unique_together={('id_grupo', 'id_asignatura')},
        ),
    ]
