# Generated by Django 5.2.1 on 2025-05-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_asignaturadocentegrupo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estudianteasignaturacursogrado',
            unique_together={('estudiante', 'asignatura', 'grupo', 'grado')},
        ),
    ]
