# Generated by Django 5.2.1 on 2025-05-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_rename_tipo_usuario_tipo_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='codigo_dane',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
