# Generated by Django 5.2.1 on 2025-05-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_sede_codigo_dane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='ponderacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
